apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-ingress
  namespace: converged
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: zerossl-production
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/acme-dns01-provider: route53
    acme.cert-manager.io/http01-edit-in-place: "true"
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/hsts-preload: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: zeorssl-helm-secret
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helm-registry
                port:
                  number: 8080