apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName}}
  labels:
    app: {{ .Values.selectorLabel }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.selectorLabel }}